[build]
  command = "npm run build"
  publish = "public"
  functions = "lambda"
  NODE_ENV = "10.15.3"
  NPM_VERSION = "6.9.0"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
